require("plug_config")
require("vim_config")
require("notify_config")
require("lualine_config")
require("misic_config")
require("theme_config")
require("browsers_config")
require("mason_config")
require("servers_config")
require("fidget_config")
require("folding")
-- require("treesitter_config")
require("signature_config")
require("snip")
require("cmp_config")
require("dap_interface")
require("refactor")
require("custom")
