local Plug = vim.fn['plug#']
vim.call('plug#begin')
-- THEMES
Plug('xiyaowong/transparent.nvim')
Plug("NLKNguyen/papercolor-theme")
Plug('chriskempson/base16-vim')
Plug('catppuccin/nvim', { as = 'catppuccin' })
Plug("ellisonleao/gruvbox.nvim")
Plug("folke/tokyonight.nvim")
Plug("kepano/flexoki-neovim")
Plug("rebelot/kanagawa.nvim")
-- BAR
Plug('nvim-lualine/lualine.nvim')
Plug('vim-airline/vim-airline')
Plug('vim-airline/vim-airline-themes')
-- SIGNATURE AND LSP
Plug('williamboman/mason-lspconfig.nvim')
Plug('williamboman/mason.nvim')
Plug('neovim/nvim-lspconfig')
Plug('hrsh7th/nvim-cmp')
Plug('hrsh7th/cmp-buffer')
Plug('hrsh7th/cmp-cmdline')
Plug('hrsh7th/cmp-nvim-lsp')
Plug('hrsh7th/cmp-path')
Plug('hrsh7th/vim-vsnip')
Plug('L3MON4D3/LuaSnip', { tag = 'v2.*', ['do'] = 'make install_jsregexp' })
Plug('nvim-treesitter/nvim-treesitter', { ['do'] = ':TSUpdate' })
Plug("rafamadriz/friendly-snippets")
Plug('saadparwaiz1/cmp_luasnip')
Plug('ray-x/lsp_signature.nvim')
Plug('windwp/nvim-autopairs')
Plug('windwp/nvim-ts-autotag')
--BROWSING
Plug('nvim-lua/plenary.nvim')
Plug('nvim-telescope/telescope-dap.nvim')
Plug('nvim-telescope/telescope.nvim')
Plug('nvim-tree/nvim-tree.lua')
Plug('nvim-tree/nvim-web-devicons')
-- QOL
Plug("lewis6991/gitsigns.nvim")
Plug('Civitasv/cmake-tools.nvim')
Plug("lukas-reineke/indent-blankline.nvim")
Plug('iamcco/markdown-preview.nvim', { ['do'] = 'cd app && yarn install' })
Plug('KarimElghamry/vim-auto-comment')
Plug('tpope/vim-fugitive')
-- DEBUGGING
Plug('mfussenegger/nvim-dap')
Plug('mfussenegger/nvim-dap-python')
Plug('rcarriga/nvim-dap-ui')
Plug('theHamsta/nvim-dap-virtual-text')
--OTHER
Plug('nvim-neotest/nvim-nio')


vim.call('plug#end')
